name: CI

on:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check || npm run tsc || echo "No type-check script found"

      - name: Lint
        run: npm run lint || echo "No lint script found"

      - name: Test
        run: npm test || echo "No test script found"

      - name: Build
        run: npm run build

      # Cache dependencies
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # Optional: Add code coverage reporting
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: hashFiles('coverage/**/*') != ''
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
